dataset: 2s3z/medium
env: sc2
pretrain_tasks:
- 2s3z
pretrain_tasks_data_quality:
  2s3z: medium
task: marine-easy-medium
test_tasks:
- 2s3z
test_tasks_data_quality: {}
train_tasks:
- 2s3z
train_tasks_data_quality:
  2s3z: medium
