dataset: 3s_vs_5z/expert
env: sc2
pretrain_tasks:
- 3s_vs_5z
pretrain_tasks_data_quality:
  3s_vs_5z: expert
task: marine-easy-expert
test_tasks:
- 3s_vs_5z
test_tasks_data_quality: {}
train_tasks:
- 3s_vs_5z
train_tasks_data_quality:
  3s_vs_5z: expert
