dataset: 5m_vs_6m/expert
env: sc2
pretrain_tasks:
- 5m_vs_6m
pretrain_tasks_data_quality:
  5m_vs_6m: expert
task: marine-easy-expert
test_tasks:
- 5m_vs_6m
test_tasks_data_quality: {}
train_tasks:
- 5m_vs_6m
train_tasks_data_quality:
  5m_vs_6m: expert
