dataset: 6h_vs_8z/medium
env: sc2
pretrain_tasks:
- 6h_vs_8z
pretrain_tasks_data_quality:
  6h_vs_8z: medium
task: marine-easy-medium
test_tasks:
- 6h_vs_8z
test_tasks_data_quality: {}
train_tasks:
- 6h_vs_8z
train_tasks_data_quality:
  6h_vs_8z: medium
