dataset: 8m/expert
env: sc2
pretrain_tasks:
- 8m
pretrain_tasks_data_quality:
  8m: expert
task: marine-easy-expert
test_tasks:
- 8m
test_tasks_data_quality: {}
train_tasks:
- 8m
train_tasks_data_quality:
  8m: expert
