dataset: 9m_vs_10m/medium-medium-replay
env: sc2
pretrain_tasks:
- 9m_vs_10m
pretrain_tasks_data_quality:
  9m_vs_10m: medium-replay
task: marine-easy-medium-replay
test_tasks:
- 9m_vs_10m
test_tasks_data_quality: {}
train_tasks:
- 9m_vs_10m
train_tasks_data_quality:
  9m_vs_10m: medium-replay
