dataset: 9m_vs_10m/expert
env: sc2
pretrain_tasks:
- 9m_vs_10m
pretrain_tasks_data_quality:
  9m_vs_10m: expert
task: marine-easy-expert
test_tasks:
- 9m_vs_10m
test_tasks_data_quality: {}
train_tasks:
- 9m_vs_10m
train_tasks_data_quality:
  9m_vs_10m: expert
